name: Compile CLI Tools
on:
  release:
    types: [published]

jobs:

  linux-cli-builder:
    name: Build Linux CLI Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Setup Environment
      run: |
        pip3 install -r ./requirements.txt
        pip3 install pyinstaller==5.6.2
    - name: build artifacts
      run: pyinstaller --onefile --clean ./masked_ai/masker.py
    - name: Make artifacts downloadable
      uses: actions/upload-artifact@v3
      with:
        name: linux-cli
        path: ./dist/masker
    
  windows-cli-builder:
    name: Build Windows CLI Release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Setup Environment
      run: |
        pip3 install -r ./requirements.txt
        pip3 install pyinstaller==5.6.2
    - name: build artifacts
      run: pyinstaller --onefile --clean .\masked_ai\masker.py
    - name: Make artifacts downloadable
      uses: actions/upload-artifact@v3
      with:
        name: windows-cli
        path: ./dist/masker
  
  macos-cli-builder:
    name: Build MacOS CLI Release
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Setup Environment
      run: |
        pip3 install -r ./requirements.txt
        pip3 install pyinstaller==5.6.2
    - name: build artifacts
      run: pyinstaller --onefile --clean --target-arch universal2 ./masked_ai/masker.py
    - name: Make artifacts downloadable
      uses: actions/upload-artifact@v3
      with:
        name: macos-cli
        path: ./dist/masker
